In [1]:
import yfinance as yf

# Download historical data for required stocks
tickers = ["MSFT","AAPL","GOOG"]
ohlcv_data = {}

# looping over tickers and storing OHLCV dataframe in dictionary
for ticker in tickers:
    temp = yf.download(ticker,period='1mo',interval='15m')
    temp.dropna(how="any",inplace=True)
    ohlcv_data[ticker] = temp

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [13]:
def ATR(DF, n=14):
    "function to calculate True Range and Average True Range"
    df = DF.copy()
    df["H-L"] = df["High"] - df["Low"]
    df["H-PC"] = abs(df["High"] - df["Adj Close"].shift(1))
    df["L-PC"] = abs(df["Low"] - df["Adj Close"].shift(1))
    df["TR"] = df[["H-L","H-PC","L-PC"]].max(axis=1, skipna=False)
    df["ATR"] = df["TR"].ewm(com=n, min_periods=n).mean()
    return df["ATR"]

In [14]:
for ticker in ohlcv_data:
    ohlcv_data[ticker]["ATR"] = ATR(ohlcv_data[ticker])

In [15]:
ohlcv_data

{'MSFT':                            Open        High         Low       Close  \
 Datetime
 2022-10-03 09:30:00  235.410004  236.500000  234.929993  235.619995
 2022-10-03 09:45:00  236.250000  237.119995  234.660004  234.945007
 2022-10-03 10:00:00  234.975006  236.919998  234.975006  235.869995
 2022-10-03 10:15:00  235.899994  237.314697  235.809998  237.132004
 2022-10-03 10:30:00  237.139999  237.740005  237.139999  237.720596
 ...                         ...         ...         ...         ...
 2022-10-31 15:00:00  232.770004  233.043106  232.050003  232.289993
 2022-10-31 15:15:00  232.279999  232.729996  232.020004  232.639999
 2022-10-31 15:30:00  232.639999  233.270004  232.559998  232.964996
 2022-10-31 15:45:00  232.949997  233.080002  231.490005  232.130005
 2022-10-31 16:00:00  232.130005  232.130005  232.130005  232.130005

                       Adj Close    Volume       ATR
 Datetime
 2022-10-03 09:30:00  235.619995   2269479       NaN
 2022-10-03 09:45:00  234.945007   1320008       NaN
 2022-10-03 10:00:00  235.869995   1194709       NaN
 2022-10-03 10:15:00  237.132004    861741       NaN
 2022-10-03 10:30:00  237.720596   1122049       NaN
 ...                         ...       ...       ...
 2022-10-31 15:00:00  232.289993  16780696  0.886108
 2022-10-31 15:15:00  232.639999    614124  0.874367
 2022-10-31 15:30:00  232.964996    961207  0.863409
 2022-10-31 15:45:00  232.130005   3024763  0.911849
 2022-10-31 16:00:00  232.130005         0  0.851059

 [547 rows x 7 columns],
 'AAPL':                            Open        High         Low       Close  \
 Datetime
 2022-10-03 09:30:00  138.210007  139.320007  137.684998  138.664993
 2022-10-03 09:45:00  139.000000  139.449997  138.792007  139.410004
 2022-10-03 10:00:00  139.419998  140.440002  139.375000  139.919998
 2022-10-03 10:15:00  139.947006  141.059998  139.869995  140.899994
 2022-10-03 10:30:00  140.910004  141.389999  140.839996  141.349899
 ...                         ...         ...         ...         ...
 2022-10-31 15:00:00  153.470001  153.570007  152.619995  153.104996
 2022-10-31 15:15:00  153.100006  153.389999  152.850006  153.339996
 2022-10-31 15:30:00  153.339996  153.600006  153.130005  153.434998
 2022-10-31 15:45:00  153.434998  153.509995  152.779999  153.449997
 2022-10-31 16:00:00  153.339996  153.339996  153.339996  153.339996

                       Adj Close    Volume       ATR
 Datetime
 2022-10-03 09:30:00  138.664993  13791789       NaN
 2022-10-03 09:45:00  139.410004   6334679       NaN
 2022-10-03 10:00:00  139.919998   5848835       NaN
 2022-10-03 10:15:00  140.899994   4882128       NaN
 2022-10-03 10:30:00  141.349899   4256588       NaN
 ...                         ...       ...       ...
 2022-10-31 15:00:00  153.104996   2621257  0.739354
 2022-10-31 15:15:00  153.339996   2241414  0.726063
 2022-10-31 15:30:00  153.434998   2755747  0.708992
 2022-10-31 15:45:00  153.449997   6141781  0.710392
 2022-10-31 16:00:00  153.339996         0  0.670366

 [547 rows x 7 columns],
 'GOOG':                           Open       High        Low      Close  Adj Close  \
 Datetime
 2022-10-03 09:30:00  97.220001  97.599998  97.019997  97.504997  97.504997
 2022-10-03 09:45:00  97.489998  98.190002  97.410004  97.599998  97.599998
 2022-10-03 10:00:00  97.619904  98.386803  97.580002  97.902298  97.902298
 2022-10-03 10:15:00  97.889999  98.459999  97.739998  98.331398  98.331398
 2022-10-03 10:30:00  98.339996  98.760002  98.220001  98.760002  98.760002
 ...                        ...        ...        ...        ...        ...
 2022-10-31 15:00:00  94.730003  94.790001  94.449997  94.546898  94.546898
 2022-10-31 15:15:00  94.544998  94.760002  94.400002  94.739998  94.739998
 2022-10-31 15:30:00  94.730003  95.059998  94.650002  95.025002  95.025002
 2022-10-31 15:45:00  95.025002  95.040001  94.429901  94.650002  94.650002
 2022-10-31 16:00:00  94.660004  94.660004  94.660004  94.660004  94.660004

                       Volume       ATR
 Datetime
 2022-10-03 09:30:00  2162006       NaN
 2022-10-03 09:45:00   966572       NaN
 2022-10-03 10:00:00  1014005       NaN
 2022-10-03 10:15:00   872395       NaN
 2022-10-03 10:30:00   708855       NaN
 ...                      ...       ...
 2022-10-31 15:00:00   687631  0.355604
 2022-10-31 15:15:00   675906  0.355897
 2022-10-31 15:30:00   893614  0.359504
 2022-10-31 15:45:00  2513861  0.376210
 2022-10-31 16:00:00        0  0.351796

 [547 rows x 7 columns]}